sed-domain: blacklist FreeBSD as sed doesn't perform well

diff --git a/lib/sed-domain b/lib/sed-domain
--- a/lib/sed-domain
+++ b/lib/sed-domain
@@ -13,12 +13,16 @@ if [ ! -r "$TLDS" ]; then
   exit 1
 fi
 
+uname=`uname`
+if [ "$uname" = FreeBSD ]; then
+  echo "$0: FreeBSD sed can't handle that long regexp, sorry" 1>&2
+  exit 1
+fi
+
 tldre=$(sed -E '/^#/d; y/ABCDEFGHIJKLMNOPQRSTUVWXYZ/abcdefghijklmnopqrstuvwxyz/' "${TLDS}" | tr '\n' '|')
 tldre="${tldre%%|}"
 
 exec sed -E \
   -e 's!,$!!; s!%e1%ba%b9!e!; s!\.ru\\.\+!\.ru!' \
-  -e '/[^-a-z0-9_.]/ w /dev/stderr' \
-  -e '/[^-a-z0-9_.]/ d' \
-  -e '/(\.|^)('"${tldre}"')$/ ! w /dev/stderr' \
-  -e '/(\.|^)('"${tldre}"')$/ ! d'
+  -e '/[^-a-z0-9_.]/ { w /dev/stderr' -e 'd }' \
+  -e '/(\.|^)('"${tldre}"')$/ ! { w /dev/stderr' -e 'd }'
